services:
  pdfedit:
    build:
      context: .
      dockerfile: src/PdfEdit.Api/Dockerfile
    container_name: pdfedit
    ports:
      - "80:80"
      - "443:443"
    environment:
      ASPNETCORE_ENVIRONMENT: Development  # <-- Add this line
    networks:
      - pdfedit-network

networks:
  pdfedit-network:
    driver: bridge

volumes:
  pdf-data: